### ISSUE TITLE
Laser scan

### ISSUE THREAD

**Issue by severin-lemaignan** [zayfod/pycozmo#14]
Any idea whether we can access to the laser scans?

The Cozmo SDK exports an occupancy map (I assume built internally from the laser scans), but does not mention anywhere an access to the raw scans (which would be tremendously useful for ROS integration)

**Comment by severin-lemaignan** [comment]
[I'm just realising that I'm referring to Vector, not Cozmo here... Does pycozmo supports Vector?]

**Comment by CozmoCyke** [comment]
Hello Séverin ,
No. PyCozmo is supporting only the Anki Cosmo Robot.
Perhaps one day we can get a PyVector ;-)

**Comment by zayfod** [comment]
Cozmo does not have a laser range detector.

PyCozmo targets only Anki Cozmo, due to the fact that the SDK communication interfaces of Cozmo and Vector differ conceptually and significantly.
