### ISSUE TITLE
Typo in functions.md 8-bit instead 16-bit

### ISSUE THREAD

**Issue by CozmoCyke** [zayfod/pycozmo#26]
In the documentation , you can find the sentence :

Speaker
The OutputAudio message can be used to transmit 744 audio samples at a time. The samples are 8-bit and u-law encoded.

must be replaced by

The OutputAudio message can be used to transmit 744 audio samples at a time. The samples are **16**-bit and u-law encoded.

Even 8-bit wave files could be played , they are not supported now. Only 16-bit,22.05 Khz or 48 Khz mono are supported now.  If these conditions are not fullfilled : an error is displayed
**ValueError: Invalid audio format, only 16 bit samples are supported, with 22050Hz or 48000Hz frame rates.**

In the script example audio.py , there's no error ; 16-bit is mentionned in the comment.

**Comment by zayfod** [comment]
Thanks for the report.

The documentation is correct.

The Cozmo robot expects `OutputAudio` messages that contain 744 *8-bit* samples that contain [u-law](https://en.wikipedia.org/wiki/%CE%9C-law_algorithm) encoded audio.

The implementation of the encoding algorithm in PyCozmo takes *16-bit raw PCM samples* and converts them to *8-bit u-law encoded samples*, that end up in `OutputAudio` messages.

Today, PyCozmo can use signed, 16-bit, 22.5 kHz PCM WAVE files as input, encodes them on-the-fly and sends them to the robot.
