### ISSUE TITLE
Python 3.5 doesn't accept the long option in setup.py

### ISSUE THREAD

**Issue by CozmoCyke** [zayfod/pycozmo#3]
C:\dev\cozmo\pycozmo>python setup.py clean
C:\Users\didie\AppData\Local\Programs\Python\Python35\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running clean

I've fixed this error with removing the long_desciption options in setup.py
    #long_description=get_readme(),
    #long_description_content_type="text/markdown",

**Comment by zayfod** [comment]
This is not related to the Python version but to the version of `setuptools`. `long_description_content_type` has been introduced in v38.6.0 and you happened to have an older one.

`setuptools` can be upgraded with:
```
pip install --upgrade setuptools
```

Added version checking with 8f437f29
