### ISSUE TITLE
please read

### ISSUE THREAD

**Issue by cozmo14047** [zayfod/pycozmo#60]
@zayfod hi there i am wanting to make a new resporitory using this code to make a new app for cozmo and to help fix some issues would you allow me to do this many thanks

**Comment by Sojens** [comment]
This is allowed under the license (MIT license), as long as you copy the LICENSE.md file into your forked repository.

**Comment by cozmo14047** [comment]
> This is allowed under the license (MIT license), as long as you copy the LICENSE.md file into your forked repository.

thanks
